/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccesibilidadRouteImport } from './routes/accesibilidad'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagosRealizadosRouteImport } from './routes/pagos.realizados'
import { Route as PagosHistorialRouteImport } from './routes/pagos.historial'
import { Route as PagosCategorySubcategoryRouteImport } from './routes/pagos.$category.$subcategory'

const AccesibilidadRoute = AccesibilidadRouteImport.update({
  id: '/accesibilidad',
  path: '/accesibilidad',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagosRealizadosRoute = PagosRealizadosRouteImport.update({
  id: '/pagos/realizados',
  path: '/pagos/realizados',
  getParentRoute: () => rootRouteImport,
} as any)
const PagosHistorialRoute = PagosHistorialRouteImport.update({
  id: '/pagos/historial',
  path: '/pagos/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const PagosCategorySubcategoryRoute =
  PagosCategorySubcategoryRouteImport.update({
    id: '/pagos/$category/$subcategory',
    path: '/pagos/$category/$subcategory',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accesibilidad': typeof AccesibilidadRoute
  '/pagos/historial': typeof PagosHistorialRoute
  '/pagos/realizados': typeof PagosRealizadosRoute
  '/pagos/$category/$subcategory': typeof PagosCategorySubcategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accesibilidad': typeof AccesibilidadRoute
  '/pagos/historial': typeof PagosHistorialRoute
  '/pagos/realizados': typeof PagosRealizadosRoute
  '/pagos/$category/$subcategory': typeof PagosCategorySubcategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accesibilidad': typeof AccesibilidadRoute
  '/pagos/historial': typeof PagosHistorialRoute
  '/pagos/realizados': typeof PagosRealizadosRoute
  '/pagos/$category/$subcategory': typeof PagosCategorySubcategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accesibilidad'
    | '/pagos/historial'
    | '/pagos/realizados'
    | '/pagos/$category/$subcategory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accesibilidad'
    | '/pagos/historial'
    | '/pagos/realizados'
    | '/pagos/$category/$subcategory'
  id:
    | '__root__'
    | '/'
    | '/accesibilidad'
    | '/pagos/historial'
    | '/pagos/realizados'
    | '/pagos/$category/$subcategory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesibilidadRoute: typeof AccesibilidadRoute
  PagosHistorialRoute: typeof PagosHistorialRoute
  PagosRealizadosRoute: typeof PagosRealizadosRoute
  PagosCategorySubcategoryRoute: typeof PagosCategorySubcategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/accesibilidad': {
      id: '/accesibilidad'
      path: '/accesibilidad'
      fullPath: '/accesibilidad'
      preLoaderRoute: typeof AccesibilidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagos/realizados': {
      id: '/pagos/realizados'
      path: '/pagos/realizados'
      fullPath: '/pagos/realizados'
      preLoaderRoute: typeof PagosRealizadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagos/historial': {
      id: '/pagos/historial'
      path: '/pagos/historial'
      fullPath: '/pagos/historial'
      preLoaderRoute: typeof PagosHistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagos/$category/$subcategory': {
      id: '/pagos/$category/$subcategory'
      path: '/pagos/$category/$subcategory'
      fullPath: '/pagos/$category/$subcategory'
      preLoaderRoute: typeof PagosCategorySubcategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesibilidadRoute: AccesibilidadRoute,
  PagosHistorialRoute: PagosHistorialRoute,
  PagosRealizadosRoute: PagosRealizadosRoute,
  PagosCategorySubcategoryRoute: PagosCategorySubcategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
